markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Amirol Ahmad
production_url : http://amirolahmad.github.io
description: "Througths, flamewars, utilities, tutorials, codes, projects and other things by Amirol Ahmad."
disqus_shortname: amirolahmadblog
# analytics: UA-32899481-1
# gauges: 50f1f940613f5d2cfe000026
author :
  name : Amirol Ahmad
  github : AmirolAhmad
  twitter : AmirolAhmad
  email: 9w2pdf@gmail.com
timezone: Asia/Kuala_Lumpur
# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%F %a"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
exclude: ["vendor"]
